# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoodWork' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoodWork

  target 'GoodWorkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoodWorkUITests' do
    # Pods for testing
  end

  pod 'IQKeyboardManagerSwift'
  pod 'SwiftyAttributes'
  pod 'NotificationBannerSwift', '~> 3.0.0'
  pod "ExpandableLabel"
  pod 'KMPlaceholderTextView', '~> 1.4.0'
  pod 'Alamofire', '~> 4.0'
  pod 'SwiftLoader'
  pod 'RangeSeekSlider'
  pod 'SDWebImage'
  pod 'DropDown'
  pod 'Charts'
  
end
